keys:
  - &users:
    - &jannis age13ufzp8nf6vm9g53slxw684gtej0lchkrdn98327rluv3wrk26q8q9axxqf
  - &hosts:
    - &MacBook-Pro age1y3u8agtuu5nshfapptrex0892aul7vw9mp2767l98n8n5er4vsgq3ypvq4

creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *jannis
        - *MacBook-Pro
